//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTutorial
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAddress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentAddress()
        {
            this.AddressInfo = new AddressCompl();
        }
    
        public int StudentAddressId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> StandardId { get; set; }
    
        public AddressCompl AddressInfo { get; set; }
    
        public virtual Standard Standard { get; set; }
        public virtual Student Student { get; set; }
    }
}
